swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine

securityDefinitions:
  basicAuth:
    description: OpenStack Keystone Authentication
    type: basic

security:
  - basicAuth: []
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - multipart/form-data
# format of the responses to the client (Accepts)
produces:
  - application/json
  - multipart/form-data
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
          default: jaeguk
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /upload:
    x-swagger-router-controller: hello
    post:
      summary: Uploads a file.
      security:
        - basicAuth: []
      consumes:
        - multipart/form-data
      operationId: createImage
      parameters:
        - in: formData
          name: file
          type: file
          description: The file to upload.
      responses:
        201: 
          description: SuccessFul request
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string

  SuccessResponse:
    properties:
      id:
        type: string
      extension:
        type: string
      size:
        type: integer
      type:
        type: string

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
